# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_gene_to_geneset_scores <- function(n_gs, gs_index, gs_geneindex, gene_score) {
    .Call(`_goat_rcpp_gene_to_geneset_scores`, n_gs, gs_index, gs_geneindex, gene_score)
}

rcpp_geneset_null <- function(gene_scores, geneset_sizes, max_geneset_size, niter) {
    .Call(`_goat_rcpp_geneset_null`, gene_scores, geneset_sizes, max_geneset_size, niter)
}

rcpp_null_distributions <- function(gene_scores, geneset_sizes, max_geneset_size, niter) {
    .Call(`_goat_rcpp_null_distributions`, gene_scores, geneset_sizes, max_geneset_size, niter)
}

rcpp_dsnorm_logsum <- function(x_min_mean, N, xi, sd) {
    .Call(`_goat_rcpp_dsnorm_logsum`, x_min_mean, N, xi, sd)
}

